import React from 'react';
import { Col, Container, Row, Table } from 'react-bootstrap';

function AboutUs() {
  return (
    <Container>
      <Row>
        <Col md={2}></Col>
        <Col md={8}>
          <Row className="mt-5">
            <div className="mt-5">
              <p>
                To demonstrate the skills acquired in the CICE FRONT END Module,
                an e-commerce SPA has been developed using the create-react-app
                framework based on ReactJS.{' '}
              </p>
              <p>
                The design and visual components were implemented using
                react-bootstrap and css language, while the store information
                was provided by a free to use API. The color palette was
                generated by Bootstrap UI and was implemented using the
                Bootstrap 4 Color Utility Generator to override the standard
                Bootstrap values and shades.{' '}
              </p>
              <p>
                The code of this project was made thanks to the information
                provided by the CICE instructors and other support material that
                will be referenced below.
              </p>
            </div>
          </Row>
          <Table className="mt-3" responsive>
            <tr>
              <td>API</td>
              <td>https://dummyjson.com/</td>
            </tr>
            <tr>
              <td>Colors</td>
              <td>https://lingtalfi.com/bootstrap4-color-generator</td>
            </tr>
            <tr>
              <td>Shopping Cart</td>
              <td>
                https://www.youtube.com/watch?v=AmIdY1Eb8tY&ab_channel=CodingwithBasir
              </td>
            </tr>
            <tr>
              <td>Pagination</td>
              <td>
                https://www.youtube.com/watch?v=IYCa1F-OWmk&ab_channel=TraversyMedia
              </td>
            </tr>
            <tr>
              <td>Images</td>
              <td>https://www.pexels.com/</td>
            </tr>
            <tr>
              <td>Icons</td>
              <td>https://react-icons.github.io/react-icons</td>
            </tr>
          </Table>
          <Row>
            <div className="mt-5">
              <p>
                If you want to use the login option, feel free to use the
                following user or refer to the API documentation
              </p>
              <div className='text-center'>
              <p className='mb-0'>Email: atuny0@sohu.com </p>
              <p>Password: 9uQFF1Lh</p></div>
            </div>
          </Row>
        </Col>
        <Col md={2}></Col>
      </Row>
    </Container>
  );
}

export default AboutUs;
