let biblioteca = {
  usuario: {
    nombre: 'Antonio',
    vip: false,
    imagen:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgSmojUgwjIB87c4Q0hLCAyl__oiTySWGWJUZtUNHlHjBALLzTsu_vMHYMaEwLts4QEoo&usqp=CAU',
  },

  libros: [
    {
      id: 1342,
      title: 'Pride and Prejudice',
      authors: [
        {
          name: 'Austen, Jane',
          birth_year: 1775,
          death_year: 1817,
        },
      ],
      translators: [],
      subjects: [
        'Courtship -- Fiction',
        'Domestic fiction',
        'England -- Fiction',
        'Love stories',
        'Sisters -- Fiction',
        'Social classes -- Fiction',
        'Young women -- Fiction',
      ],
      bookshelves: ['Best Books Ever Listings', 'Harvard Classics'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1342.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1342.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1342.rdf',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/1342/1342-h.zip',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1342/1342-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1342/pg1342.cover.small.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/1342.html.images',
      },
      download_count: 34176,
    },
    {
      id: 11,
      title: "Alice's Adventures in Wonderland",
      authors: [
        {
          name: 'Carroll, Lewis',
          birth_year: 1832,
          death_year: 1898,
        },
      ],
      translators: [],
      subjects: [
        'Alice (Fictitious character from Carroll) -- Juvenile fiction',
        "Children's stories",
        'Fantasy fiction',
        'Imaginary places -- Juvenile fiction',
      ],
      bookshelves: ["Children's Literature"],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/11.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/11.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/11.kindle.images',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/11/11-h.zip',
        'application/zip': 'https://www.gutenberg.org/files/11/11-0.zip',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/11/11-0.txt',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/11/pg11.cover.small.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/11.html.images',
      },
      download_count: 21051,
    },
    {
      id: 1661,
      title: 'The Adventures of Sherlock Holmes',
      authors: [
        {
          name: 'Doyle, Arthur Conan',
          birth_year: 1859,
          death_year: 1930,
        },
      ],
      translators: [],
      subjects: [
        'Detective and mystery stories, English',
        'Holmes, Sherlock (Fictitious character) -- Fiction',
        'Private investigators -- England -- Fiction',
      ],
      bookshelves: [
        "Banned Books from Anne Haight's list",
        'Contemporary Reviews',
        'Detective Fiction',
      ],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1661.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1661.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1661.kindle.images',
        'application/zip': 'https://www.gutenberg.org/files/1661/1661-h.zip',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1661/1661-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1661/pg1661.cover.small.jpg',
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/1661/1661-h/1661-h.htm',
        'text/html': 'https://www.gutenberg.org/ebooks/1661.html.images',
      },
      download_count: 19655,
    },
    {
      id: 20228,
      title: 'Noli Me Tangere',
      authors: [
        {
          name: 'Rizal, José',
          birth_year: 1861,
          death_year: 1896,
        },
      ],
      translators: [
        {
          name: 'Poblete, Pascual Hicaro',
          birth_year: 1857,
          death_year: 1921,
        },
      ],
      subjects: ['Historical fiction', 'Philippines -- History -- 1812-1898 -- Fiction'],
      bookshelves: [],
      languages: ['tl'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/20228.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/20228.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/20228.epub.images',
        'text/plain': 'https://www.gutenberg.org/ebooks/20228.txt.utf-8',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/20228/pg20228.cover.medium.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/20228.html.images',
        'text/html; charset=iso-8859-1':
          'https://www.gutenberg.org/files/20228/20228-h/20228-h.htm',
        'text/plain; charset=iso-8859-1':
          'https://www.gutenberg.org/files/20228/20228-8.zip',
        'application/zip': 'https://www.gutenberg.org/files/20228/20228-h.zip',
      },
      download_count: 19516,
    },
    {
      id: 84,
      title: 'Frankenstein; Or, The Modern Prometheus',
      authors: [
        {
          name: 'Shelley, Mary Wollstonecraft',
          birth_year: 1797,
          death_year: 1851,
        },
      ],
      translators: [],
      subjects: [
        "Frankenstein's monster (Fictitious character) -- Fiction",
        'Frankenstein, Victor (Fictitious character) -- Fiction',
        'Gothic fiction',
        'Horror tales',
        'Monsters -- Fiction',
        'Science fiction',
        'Scientists -- Fiction',
      ],
      bookshelves: [
        'Gothic Fiction',
        'Movie Books',
        'Precursors of Science Fiction',
        'Science Fiction by Women',
      ],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/84/84-0.txt',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/84.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/84.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/84.kindle.images',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/84/84-h.zip',
        'application/zip': 'https://www.gutenberg.org/files/84/84-0.zip',
        'text/html': 'https://www.gutenberg.org/ebooks/84.html.images',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg',
      },
      download_count: 17482,
    },
    {
      id: 2701,
      title: 'Moby Dick; Or, The Whale',
      authors: [
        {
          name: 'Melville, Herman',
          birth_year: 1819,
          death_year: 1891,
        },
      ],
      translators: [],
      subjects: [
        'Adventure stories',
        'Ahab, Captain (Fictitious character) -- Fiction',
        'Mentally ill -- Fiction',
        'Psychological fiction',
        'Sea stories',
        'Ship captains -- Fiction',
        'Whales -- Fiction',
        'Whaling -- Fiction',
        'Whaling ships -- Fiction',
      ],
      bookshelves: ['Best Books Ever Listings'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/2701/2701-h/2701-h.htm',
        'application/zip': 'https://www.gutenberg.org/files/2701/2701-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/2701/pg2701.cover.small.jpg',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/2701.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2701.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/2701.epub.images',
        'text/html': 'https://www.gutenberg.org/ebooks/2701.html.images',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/2701/2701-0.txt',
      },
      download_count: 13735,
    },
    {
      id: 345,
      title: 'Dracula',
      authors: [
        {
          name: 'Stoker, Bram',
          birth_year: 1847,
          death_year: 1912,
        },
      ],
      translators: [],
      subjects: [
        'Dracula, Count (Fictitious character) -- Fiction',
        'Epistolary fiction',
        'Gothic fiction',
        'Horror tales',
        'Transylvania (Romania) -- Fiction',
        'Vampires -- Fiction',
        'Whitby (England) -- Fiction',
      ],
      bookshelves: ['Gothic Fiction', 'Horror', 'Movie Books', 'Mystery Fiction'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/plain': 'https://www.gutenberg.org/ebooks/345.txt.utf-8',
        'text/html': 'https://www.gutenberg.org/files/345/345-h/345-h.htm',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/345.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/345.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/345.kindle.images',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/345/pg345.cover.small.jpg',
        'application/zip': 'https://www.gutenberg.org/files/345/345-h.zip',
        'application/octet-stream': 'https://www.gutenberg.org/files/345/345-0.zip',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/345/345-0.txt',
      },
      download_count: 13196,
    },
    {
      id: 4300,
      title: 'Ulysses',
      authors: [
        {
          name: 'Joyce, James',
          birth_year: 1882,
          death_year: 1941,
        },
      ],
      translators: [],
      subjects: [
        'Alienation (Social psychology) -- Fiction',
        'Artists -- Fiction',
        'City and town life -- Fiction',
        'Domestic fiction',
        'Dublin (Ireland) -- Fiction',
        'Epic literature',
        'Jewish men -- Fiction',
        'Male friendship -- Fiction',
        'Married people -- Fiction',
        'Psychological fiction',
      ],
      bookshelves: [
        'Banned Books List from the American Library Association',
        "Banned Books from Anne Haight's list",
        'Best Books Ever Listings',
        'Erotic Fiction',
      ],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/4300/4300-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/4300/pg4300.cover.medium.jpg',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/4300.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/4300.epub.images',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/4300.kindle.images',
        'text/html': 'https://www.gutenberg.org/ebooks/4300.html.images',
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/4300/4300-h/4300-h.htm',
      },
      download_count: 12658,
    },
    {
      id: 174,
      title: 'The Picture of Dorian Gray',
      authors: [
        {
          name: 'Wilde, Oscar',
          birth_year: 1854,
          death_year: 1900,
        },
      ],
      translators: [],
      subjects: [
        'Appearance (Philosophy) -- Fiction',
        'Conduct of life -- Fiction',
        'Didactic fiction',
        'Great Britain -- History -- Victoria, 1837-1901 -- Fiction',
        'London (England) -- History -- 1800-1950 -- Fiction',
        'Paranormal fiction',
        'Portraits -- Fiction',
        'Supernatural -- Fiction',
      ],
      bookshelves: ['Gothic Fiction', 'Movie Books'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/174.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/174.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/174.kindle.images',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/174/pg174.cover.small.jpg',
        'application/octet-stream': 'https://www.gutenberg.org/files/174/174-0.zip',
        'text/html': 'https://www.gutenberg.org/files/174/174-h/174-h.htm',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/174/174-0.txt',
        'application/zip': 'https://www.gutenberg.org/files/174/174-h.zip',
        'text/plain': 'https://www.gutenberg.org/ebooks/174.txt.utf-8',
      },
      download_count: 11714,
    },
    {
      id: 1952,
      title: 'The Yellow Wallpaper',
      authors: [
        {
          name: 'Gilman, Charlotte Perkins',
          birth_year: 1860,
          death_year: 1935,
        },
      ],
      translators: [],
      subjects: [
        'Feminist fiction',
        'Married women -- Psychology -- Fiction',
        'Mentally ill women -- Fiction',
        'Psychological fiction',
        'Sex role -- Fiction',
      ],
      bookshelves: ['Gothic Fiction'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1952/1952-0.txt',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1952.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1952.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1952.epub.images',
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/1952/1952-h/1952-h.htm',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1952/pg1952.cover.small.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/1952.html.images',
      },
      download_count: 11307,
    },
    {
      id: 98,
      title: 'A Tale of Two Cities',
      authors: [
        {
          name: 'Dickens, Charles',
          birth_year: 1812,
          death_year: 1870,
        },
      ],
      translators: [],
      subjects: [
        'British -- France -- Paris -- Fiction',
        'Executions and executioners -- Fiction',
        'France -- History -- Revolution, 1789-1799 -- Fiction',
        'French -- England -- London -- Fiction',
        'Historical fiction',
        'London (England) -- History -- 18th century -- Fiction',
        'Lookalikes -- Fiction',
        'Paris (France) -- History -- 1789-1799 -- Fiction',
        'War stories',
      ],
      bookshelves: ['Historical Fiction'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/98.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/98.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/98.kindle.images',
        'application/zip': 'https://www.gutenberg.org/files/98/98-0.zip',
        'text/html': 'https://www.gutenberg.org/ebooks/98.html.images',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/98/98-0.txt',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/98/pg98.cover.medium.jpg',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/98/98-h/98-h.htm',
      },
      download_count: 10791,
    },
    {
      id: 32449,
      title: 'Japanese Girls and Women: Revised and Enlarged Edition',
      authors: [
        {
          name: 'Bacon, Alice Mabel',
          birth_year: 1858,
          death_year: 1918,
        },
      ],
      translators: [],
      subjects: [
        'Japan -- Social life and customs -- 1868-1912',
        'Women -- Japan -- Social conditions',
        'Women -- Japan -- Social life and customs',
      ],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/32449/32449-h/32449-h.htm',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/32449/32449-0.txt',
        'text/html': 'https://www.gutenberg.org/ebooks/32449.html.images',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/32449.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/32449.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/32449.epub.images',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/32449/pg32449.cover.medium.jpg',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/32449/32449.txt',
        'text/plain; charset=iso-8859-1':
          'https://www.gutenberg.org/files/32449/32449-8.zip',
        'application/zip': 'https://www.gutenberg.org/files/32449/32449-0.zip',
      },
      download_count: 10632,
    },
    {
      id: 64317,
      title: 'The Great Gatsby',
      authors: [
        {
          name: 'Fitzgerald, F. Scott (Francis Scott)',
          birth_year: 1896,
          death_year: 1940,
        },
      ],
      translators: [],
      subjects: [
        'First loves -- Fiction',
        'Long Island (N.Y.) -- Fiction',
        'Married women -- Fiction',
        'Psychological fiction',
        'Rich people -- Fiction',
      ],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html': 'https://www.gutenberg.org/ebooks/64317.html.images',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/64317.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/64317.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/64317.epub.images',
        'application/octet-stream': 'https://www.gutenberg.org/files/64317/64317-0.zip',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/64317/pg64317.cover.small.jpg',
        'application/zip': 'https://www.gutenberg.org/files/64317/64317-h.zip',
        'text/plain': 'https://www.gutenberg.org/ebooks/64317.txt.utf-8',
        'text/plain; charset=us-ascii':
          'https://www.gutenberg.org/files/64317/64317-0.txt',
      },
      download_count: 10281,
    },
    {
      id: 43,
      title: 'The Strange Case of Dr. Jekyll and Mr. Hyde',
      authors: [
        {
          name: 'Stevenson, Robert Louis',
          birth_year: 1850,
          death_year: 1894,
        },
      ],
      translators: [],
      subjects: [
        'Horror tales',
        'London (England) -- Fiction',
        'Multiple personality -- Fiction',
        'Physicians -- Fiction',
        'Psychological fiction',
        'Science fiction',
        'Self-experimentation in medicine -- Fiction',
      ],
      bookshelves: ['Horror', 'Movie Books', 'Precursors of Science Fiction'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/43/43-h/43-h.htm',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/43.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/43.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/43.kindle.images',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/43/43-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/43/pg43.cover.medium.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/43.html.images',
      },
      download_count: 8584,
    },
    {
      id: 1400,
      title: 'Great Expectations',
      authors: [
        {
          name: 'Dickens, Charles',
          birth_year: 1812,
          death_year: 1870,
        },
      ],
      translators: [],
      subjects: [
        'Benefactors -- Fiction',
        'Bildungsromans',
        'England -- Fiction',
        'Ex-convicts -- Fiction',
        'Man-woman relationships -- Fiction',
        'Orphans -- Fiction',
        'Revenge -- Fiction',
        'Young men -- Fiction',
      ],
      bookshelves: ['Best Books Ever Listings'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1400/pg1400.cover.medium.jpg',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1400.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1400.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1400.rdf',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1400/1400-0.txt',
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/1400/1400-h/1400-h.htm',
        'application/zip': 'https://www.gutenberg.org/files/1400/1400-h.zip',
        'text/html': 'https://www.gutenberg.org/ebooks/1400.html.images',
      },
      download_count: 8569,
    },
    {
      id: 25344,
      title: 'The Scarlet Letter',
      authors: [
        {
          name: 'Hawthorne, Nathaniel',
          birth_year: 1804,
          death_year: 1864,
        },
      ],
      translators: [],
      subjects: [
        'Adultery -- Fiction',
        'Boston (Mass.) -- History -- Colonial period, ca. 1600-1775 -- Fiction',
        'Clergy -- Fiction',
        'Historical fiction',
        'Illegitimate children -- Fiction',
        'Married women -- Fiction',
        'Psychological fiction',
        'Puritans -- Fiction',
        'Revenge -- Fiction',
        'Triangles (Interpersonal relations) -- Fiction',
        'Women immigrants -- Fiction',
      ],
      bookshelves: ["Banned Books from Anne Haight's list"],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/25344.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/25344.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/25344.epub.images',
        'text/plain': 'https://www.gutenberg.org/ebooks/25344.txt.utf-8',
        'text/plain; charset=us-ascii':
          'https://www.gutenberg.org/files/25344/25344-0.txt',
        'text/html': 'https://www.gutenberg.org/files/25344/25344-h/25344-h.htm',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/25344/pg25344.cover.medium.jpg',
        'application/octet-stream': 'https://www.gutenberg.org/files/25344/25344-0.zip',
      },
      download_count: 8547,
    },
    {
      id: 2600,
      title: 'War and Peace',
      authors: [
        {
          name: 'Tolstoy, Leo, graf',
          birth_year: 1828,
          death_year: 1910,
        },
      ],
      translators: [
        {
          name: 'Maude, Aylmer',
          birth_year: 1858,
          death_year: 1938,
        },
        {
          name: 'Maude, Louise',
          birth_year: 1855,
          death_year: 1939,
        },
      ],
      subjects: [
        'Aristocracy (Social class) -- Russia -- Fiction',
        'Historical fiction',
        'Napoleonic Wars, 1800-1815 -- Campaigns -- Russia -- Fiction',
        'Russia -- History -- Alexander I, 1801-1825 -- Fiction',
        'War stories',
      ],
      bookshelves: [
        'Best Books Ever Listings',
        'Historical Fiction',
        'Movie Books',
        'Napoleonic(Bookshelf)',
        'Opera',
      ],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/2600/pg2600.cover.medium.jpg',
        'application/octet-stream': 'https://www.gutenberg.org/files/2600/2600-h.zip',
        'text/plain': 'https://www.gutenberg.org/ebooks/2600.txt.utf-8',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/2600.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/2600.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2600.rdf',
        'text/html': 'https://www.gutenberg.org/ebooks/2600.html.images',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/2600/2600-0.txt',
      },
      download_count: 8530,
    },
    {
      id: 35899,
      title: 'The Philippines a Century Hence',
      authors: [
        {
          name: 'Rizal, José',
          birth_year: 1861,
          death_year: 1896,
        },
      ],
      translators: [
        {
          name: 'Derbyshire, Charles E.',
          birth_year: null,
          death_year: null,
        },
      ],
      subjects: ['Philippines'],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=us-ascii':
          'https://www.gutenberg.org/files/35899/35899-h/35899-h.htm',
        'application/zip': 'https://www.gutenberg.org/files/35899/35899-h.zip',
        'text/html': 'https://www.gutenberg.org/ebooks/35899.html.images',
        'text/plain; charset=iso-8859-1':
          'https://www.gutenberg.org/files/35899/35899-8.txt',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/35899.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/35899.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/35899.epub.images',
        'text/plain': 'https://www.gutenberg.org/ebooks/35899.txt.utf-8',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/35899/35899.zip',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/35899/pg35899.cover.medium.jpg',
      },
      download_count: 8334,
    },
    {
      id: 2554,
      title: 'Crime and Punishment',
      authors: [
        {
          name: 'Dostoyevsky, Fyodor',
          birth_year: 1821,
          death_year: 1881,
        },
      ],
      translators: [
        {
          name: 'Garnett, Constance',
          birth_year: 1861,
          death_year: 1946,
        },
      ],
      subjects: [
        'Crime -- Psychological aspects -- Fiction',
        'Detective and mystery stories',
        'Murder -- Fiction',
        'Psychological fiction',
        'Saint Petersburg (Russia) -- Fiction',
      ],
      bookshelves: ['Best Books Ever Listings', 'Crime Fiction', 'Harvard Classics'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/2554/pg2554.cover.medium.jpg',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/2554/2554-h.zip',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/2554.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/2554.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2554.rdf',
        'text/html': 'https://www.gutenberg.org/ebooks/2554.html.images',
        'application/zip': 'https://www.gutenberg.org/files/2554/2554-0.zip',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/2554/2554-0.txt',
      },
      download_count: 7965,
    },
    {
      id: 30254,
      title: 'The Romance of Lust: A classic Victorian erotic novel',
      authors: [
        {
          name: 'Anonymous',
          birth_year: null,
          death_year: null,
        },
      ],
      translators: [],
      subjects: [
        'Corporal punishment -- Fiction',
        'Erotic stories',
        'Incest -- Fiction',
        'Pornography',
        'Rape -- Fiction',
        'Sexual dominance and submission -- Fiction',
      ],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/30254/30254-h/30254-h.htm',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/30254.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/30254.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/30254.epub.images',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/30254/pg30254.cover.medium.jpg',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/30254/30254-0.txt',
        'text/html': 'https://www.gutenberg.org/ebooks/30254.html.images',
        'application/zip': 'https://www.gutenberg.org/files/30254/30254-0.zip',
      },
      download_count: 7808,
    },
    {
      id: 1184,
      title: 'The Count of Monte Cristo, Illustrated',
      authors: [
        {
          name: 'Dumas, Alexandre',
          birth_year: 1802,
          death_year: 1870,
        },
      ],
      translators: [],
      subjects: [
        'Adventure stories',
        'Dantès, Edmond (Fictitious character) -- Fiction',
        'France -- History -- 19th century -- Fiction',
        'Historical fiction',
        'Pirates -- Fiction',
        'Prisoners -- Fiction',
        'Revenge -- Fiction',
      ],
      bookshelves: ['Adventure', 'Movie Books'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1184.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1184.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1184.rdf',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/1184/1184-0.txt',
        'text/html': 'https://www.gutenberg.org/ebooks/1184.html.images',
        'application/zip': 'https://www.gutenberg.org/files/1184/1184-0.zip',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1184/pg1184.cover.medium.jpg',
        'application/octet-stream': 'https://www.gutenberg.org/files/1184/1184-h.zip',
        'text/plain': 'https://www.gutenberg.org/ebooks/1184.txt.utf-8',
      },
      download_count: 7794,
    },
    {
      id: 1080,
      title:
        'A Modest Proposal: For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick',
      authors: [
        {
          name: 'Swift, Jonathan',
          birth_year: 1667,
          death_year: 1745,
        },
      ],
      translators: [],
      subjects: [
        'Ireland -- Politics and government -- 18th century -- Humor',
        'Political satire, English',
        'Religious satire, English',
      ],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/1080/1080-h/1080-h.htm',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1080/pg1080.cover.small.jpg',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1080.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1080.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1080.epub.images',
        'application/zip': 'https://www.gutenberg.org/files/1080/1080-0.zip',
        'text/html': 'https://www.gutenberg.org/ebooks/1080.html.images',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1080/1080-0.txt',
      },
      download_count: 7696,
    },
    {
      id: 2591,
      title: "Grimms' Fairy Tales",
      authors: [
        {
          name: 'Grimm, Wilhelm',
          birth_year: 1786,
          death_year: 1859,
        },
        {
          name: 'Grimm, Jacob',
          birth_year: 1785,
          death_year: 1863,
        },
      ],
      translators: [],
      subjects: ['Fairy tales -- Germany'],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/2591/2591-h/2591-h.htm',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/2591/pg2591.cover.small.jpg',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/2591/2591-0.zip',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/2591.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/2591.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2591.rdf',
        'text/html': 'https://www.gutenberg.org/ebooks/2591.html.images',
      },
      download_count: 7435,
    },
    {
      id: 5200,
      title: 'Metamorphosis',
      authors: [
        {
          name: 'Kafka, Franz',
          birth_year: 1883,
          death_year: 1924,
        },
      ],
      translators: [
        {
          name: 'Wyllie, David (Translator)',
          birth_year: null,
          death_year: null,
        },
      ],
      subjects: ['Metamorphosis -- Fiction', 'Psychological fiction'],
      bookshelves: ['Horror'],
      languages: ['en'],
      copyright: true,
      media_type: 'Text',
      formats: {
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/5200/pg5200.cover.medium.jpg',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/5200/5200-0.txt',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/5200.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/5200.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/5200.kindle.images',
        'text/html; charset=iso-8859-1':
          'https://www.gutenberg.org/files/5200/5200-h/5200-h.htm',
        'text/html': 'https://www.gutenberg.org/ebooks/5200.html.images',
        'application/zip': 'https://www.gutenberg.org/files/5200/5200-h.zip',
      },
      download_count: 7403,
    },
    {
      id: 1260,
      title: 'Jane Eyre: An Autobiography',
      authors: [
        {
          name: 'Brontë, Charlotte',
          birth_year: 1816,
          death_year: 1855,
        },
      ],
      translators: [],
      subjects: [
        'Bildungsromans',
        'Charity-schools -- Fiction',
        'Country homes -- Fiction',
        'England -- Fiction',
        'Fathers and daughters -- Fiction',
        'Governesses -- Fiction',
        'Love stories',
        'Married people -- Fiction',
        'Mentally ill women -- Fiction',
        'Orphans -- Fiction',
        'Young women -- Fiction',
      ],
      bookshelves: [],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'application/zip': 'https://www.gutenberg.org/files/1260/1260-h.zip',
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/1260/1260-h/1260-h.htm',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/1260.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/1260.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/1260.epub.images',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/1260/1260-0.txt',
        'text/html': 'https://www.gutenberg.org/ebooks/1260.html.images',
      },
      download_count: 7384,
    },
    {
      id: 47629,
      title: 'Ang "Filibusterismo" (Karugtóng ng Noli Me Tangere)',
      authors: [
        {
          name: 'Rizal, José',
          birth_year: 1861,
          death_year: 1896,
        },
      ],
      translators: [
        {
          name: 'Mariano, Patricio',
          birth_year: 1877,
          death_year: 1935,
        },
      ],
      subjects: [
        'Nationalists -- Philippines -- Fiction',
        'Philippine fiction (Spanish) -- Translations into Tagalog',
        'Philippines -- History -- Fiction',
      ],
      bookshelves: [],
      languages: ['tl'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html': 'https://www.gutenberg.org/ebooks/47629.html.images',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/47629/47629-0.txt',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/47629/47629-h.zip',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/47629.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/47629.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/47629.epub.images',
        'image/jpeg':
          'https://www.gutenberg.org/cache/epub/47629/pg47629.cover.medium.jpg',
      },
      download_count: 7025,
    },
    {
      id: 2542,
      title: "A Doll's House : a play",
      authors: [
        {
          name: 'Ibsen, Henrik',
          birth_year: 1828,
          death_year: 1906,
        },
      ],
      translators: [],
      subjects: [
        'Man-woman relationships -- Drama',
        'Marriage -- Drama',
        'Norwegian drama -- Translations into English',
        'Wives -- Drama',
      ],
      bookshelves: ['Best Books Ever Listings'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html; charset=utf-8':
          'https://www.gutenberg.org/files/2542/2542-h/2542-h.htm',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/2542/2542-0.txt',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/2542/pg2542.cover.small.jpg',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/2542.kindle.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2542.rdf',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/2542.epub.images',
        'text/html': 'https://www.gutenberg.org/ebooks/2542.html.images',
      },
      download_count: 6920,
    },
    {
      id: 844,
      title: 'The Importance of Being Earnest: A Trivial Comedy for Serious People',
      authors: [
        {
          name: 'Wilde, Oscar',
          birth_year: 1854,
          death_year: 1900,
        },
      ],
      translators: [],
      subjects: [
        'Comedies',
        'England -- Drama',
        'Foundlings -- Drama',
        'Identity (Psychology) -- Drama',
      ],
      bookshelves: ['Plays'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/html': 'https://www.gutenberg.org/files/844/844-h/844-h.htm',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/844.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/844.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/844.kindle.images',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/844/pg844.cover.medium.jpg',
        'application/zip': 'https://www.gutenberg.org/files/844/844-0.zip',
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/844/844-0.txt',
      },
      download_count: 6842,
    },
    {
      id: 6130,
      title: 'The Iliad',
      authors: [
        {
          name: 'Homer',
          birth_year: -750,
          death_year: -650,
        },
      ],
      translators: [
        {
          name: 'Pope, Alexander',
          birth_year: 1688,
          death_year: 1744,
        },
      ],
      subjects: [
        'Achilles (Mythological character) -- Poetry',
        'Classical literature',
        'Epic poetry, Greek -- Translations into English',
        'Trojan War -- Poetry',
      ],
      bookshelves: ['Classical Antiquity'],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/6130/pg6130.cover.medium.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/6130.html.images',
        'application/zip': 'https://www.gutenberg.org/files/6130/6130-0.zip',
        'application/octet-stream': 'https://www.gutenberg.org/files/6130/6130-h.zip',
        'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/6130/6130-0.txt',
        'text/plain': 'https://www.gutenberg.org/ebooks/6130.txt.utf-8',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/6130.kindle.images',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/6130.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/6130.rdf',
      },
      download_count: 6823,
    },
    {
      id: 76,
      title: 'Adventures of Huckleberry Finn',
      authors: [
        {
          name: 'Twain, Mark',
          birth_year: 1835,
          death_year: 1910,
        },
      ],
      translators: [],
      subjects: [
        'Adventure stories',
        'Bildungsromans',
        'Boys -- Fiction',
        'Finn, Huckleberry (Fictitious character) -- Fiction',
        'Fugitive slaves -- Fiction',
        'Humorous stories',
        'Male friendship -- Fiction',
        'Mississippi River -- Fiction',
        'Missouri -- Fiction',
        'Race relations -- Fiction',
        'Runaway children -- Fiction',
      ],
      bookshelves: [
        'Banned Books List from the American Library Association',
        "Banned Books from Anne Haight's list",
        'Best Books Ever Listings',
      ],
      languages: ['en'],
      copyright: false,
      media_type: 'Text',
      formats: {
        'text/plain; charset=utf-8': 'https://www.gutenberg.org/files/76/76-0.txt',
        'application/epub+zip': 'https://www.gutenberg.org/ebooks/76.epub.images',
        'application/rdf+xml': 'https://www.gutenberg.org/ebooks/76.rdf',
        'application/x-mobipocket-ebook':
          'https://www.gutenberg.org/ebooks/76.kindle.images',
        'application/zip': 'https://www.gutenberg.org/files/76/76-0.zip',
        'text/html; charset=utf-8': 'https://www.gutenberg.org/files/76/76-h/76-h.htm',
        'image/jpeg': 'https://www.gutenberg.org/cache/epub/76/pg76.cover.small.jpg',
        'text/html': 'https://www.gutenberg.org/ebooks/76.html.images',
      },
      download_count: 6697,
    },
  ],
}


export default biblioteca;